-- Seed expansion: ~74 additional curated mods for claudemod.com
-- Run order: after 003_seed.sql
-- Star counts are approximate estimates; update via: UPDATE public.mods SET github_stars = <n> WHERE slug = '<slug>';

insert into public.mods (
  slug, name, description, long_description, category,
  github_url, author_github, author_name,
  tags, github_stars, is_featured, status
) values

-- ─── MCP SERVERS (16) ────────────────────────────────────────────────────────

('github-mcp-server',
 'GitHub MCP Server',
 'Official GitHub MCP server — search repos, manage issues and PRs, read files, create commits, and automate GitHub workflows directly from Claude.',
 NULL, 'mcp-server',
 'https://github.com/github/github-mcp-server', 'github', 'GitHub',
 ARRAY['github', 'mcp', 'official', 'issues', 'prs', 'repos'],
 26000, true, 'approved'),

('playwright-mcp',
 'Playwright MCP',
 'Official Microsoft Playwright MCP server — give Claude full browser automation: navigate pages, click elements, fill forms, take screenshots, and scrape content.',
 NULL, 'mcp-server',
 'https://github.com/microsoft/playwright-mcp', 'microsoft', 'Microsoft',
 ARRAY['playwright', 'browser', 'automation', 'scraping', 'screenshots', 'mcp'],
 5200, true, 'approved'),

('terraform-mcp-server',
 'Terraform MCP Server',
 'Official HashiCorp Terraform MCP server — let Claude browse the Terraform Registry, look up provider docs, and generate HCL configurations.',
 NULL, 'mcp-server',
 'https://github.com/hashicorp/terraform-mcp-server', 'hashicorp', 'HashiCorp',
 ARRAY['terraform', 'infrastructure', 'iac', 'hashicorp', 'hcl', 'mcp'],
 1800, false, 'approved'),

('notion-mcp-server',
 'Notion MCP Server',
 'Official Notion MCP server — read and write Notion pages, search your workspace, update databases, and create blocks from within Claude.',
 NULL, 'mcp-server',
 'https://github.com/makenotion/notion-mcp-server', 'makenotion', 'Notion',
 ARRAY['notion', 'notes', 'databases', 'pages', 'workspace', 'mcp'],
 2400, true, 'approved'),

('atlassian-mcp-server',
 'Atlassian MCP Server',
 'Official Atlassian MCP server — connect Claude to Jira and Confluence: create tickets, update issues, search docs, and manage projects.',
 NULL, 'mcp-server',
 'https://github.com/atlassian/atlassian-mcp-server', 'atlassian', 'Atlassian',
 ARRAY['jira', 'confluence', 'atlassian', 'tickets', 'project-management', 'mcp'],
 900, false, 'approved'),

('cloudflare-mcp-server',
 'Cloudflare MCP Server',
 'Official Cloudflare MCP server — manage Workers, KV, R2, D1, and Durable Objects. Deploy edge functions and query your Cloudflare resources from Claude.',
 NULL, 'mcp-server',
 'https://github.com/cloudflare/mcp-server-cloudflare', 'cloudflare', 'Cloudflare',
 ARRAY['cloudflare', 'workers', 'edge', 'kv', 'r2', 'mcp'],
 1200, false, 'approved'),

('awesome-mcp-servers',
 'Awesome MCP Servers',
 'The most comprehensive curated list of MCP servers — 500+ entries covering every category: databases, dev tools, cloud providers, communication, productivity, and more.',
 NULL, 'mcp-server',
 'https://github.com/punkpeye/awesome-mcp-servers', 'punkpeye', 'Frank Fiegel',
 ARRAY['awesome-list', 'curated', 'mcp', 'directory', 'community'],
 3100, true, 'approved'),

('claude-code-mcp',
 'Claude Code MCP',
 'Run Claude Code as an MCP server so other AI tools and agents can invoke it programmatically — expose Claude Code capabilities via the MCP protocol.',
 NULL, 'mcp-server',
 'https://github.com/steipete/claude-code-mcp', 'steipete', 'Peter Steinberger',
 ARRAY['claude-code', 'mcp', 'server', 'programmatic', 'integration'],
 120, false, 'approved'),

('firecrawl-mcp-server',
 'Firecrawl MCP Server',
 'MCP server for Firecrawl — give Claude powerful web scraping and crawling: extract clean markdown from any URL, crawl entire sites, and search the web.',
 NULL, 'mcp-server',
 'https://github.com/mendableai/firecrawl-mcp-server', 'mendableai', 'Mendable AI',
 ARRAY['firecrawl', 'web-scraping', 'crawling', 'markdown', 'fetch', 'mcp'],
 950, false, 'approved'),

('exa-mcp-server',
 'Exa MCP Server',
 'MCP server for Exa search API — give Claude neural web search with semantic understanding, real-time results, and rich content extraction.',
 NULL, 'mcp-server',
 'https://github.com/exa-labs/exa-mcp-server', 'exa-labs', 'Exa',
 ARRAY['search', 'exa', 'semantic-search', 'web', 'retrieval', 'mcp'],
 340, false, 'approved'),

('context7',
 'Context7 MCP',
 'MCP server by Upstash that pulls up-to-date library documentation straight into Claude context — no more hallucinated APIs, always current docs.',
 NULL, 'mcp-server',
 'https://github.com/upstash/context7', 'upstash', 'Upstash',
 ARRAY['docs', 'context', 'libraries', 'upstash', 'documentation', 'mcp'],
 420, false, 'approved'),

('n8n-mcp',
 'n8n MCP Server',
 'MCP server exposing n8n workflow automation — let Claude trigger and manage n8n workflows, access workflow data, and orchestrate automation pipelines.',
 NULL, 'mcp-server',
 'https://github.com/czlonkowski/n8n-mcp', 'czlonkowski', 'Czlonkowski',
 ARRAY['n8n', 'automation', 'workflows', 'pipelines', 'mcp'],
 50, false, 'approved'),

('mcp-knowledge-graph',
 'MCP Knowledge Graph',
 'A local knowledge graph MCP server — store entities, relationships, and facts that persist across Claude Code sessions for long-running projects.',
 NULL, 'mcp-server',
 'https://github.com/shaneholloman/mcp-knowledge-graph', 'shaneholloman', 'Shane Holloman',
 ARRAY['knowledge-graph', 'memory', 'persistence', 'entities', 'relationships', 'mcp'],
 90, false, 'approved'),

('wong2-awesome-mcp',
 'Awesome MCP Servers (wong2)',
 'Another top-tier curated MCP server list with a focus on quality over quantity — well-categorized with descriptions and install commands for each server.',
 NULL, 'mcp-server',
 'https://github.com/wong2/awesome-mcp-servers', 'wong2', 'wong2',
 ARRAY['awesome-list', 'curated', 'mcp', 'directory'],
 400, false, 'approved'),

('sequential-thinking-mcp',
 'Sequential Thinking MCP',
 'Official MCP server for structured chain-of-thought reasoning — gives Claude a scratchpad to think through complex problems step by step before answering.',
 NULL, 'mcp-server',
 'https://github.com/modelcontextprotocol/servers', 'modelcontextprotocol', 'MCP Team',
 ARRAY['chain-of-thought', 'reasoning', 'thinking', 'official', 'mcp'],
 2100, false, 'approved'),

('claude-context',
 'Claude Context MCP',
 'Zilliz MCP server that connects Claude to Milvus vector databases — semantic search over your own data, RAG pipelines, and similarity lookups.',
 NULL, 'mcp-server',
 'https://github.com/zilliztech/claude-context', 'zilliztech', 'Zilliz',
 ARRAY['vector-db', 'milvus', 'rag', 'semantic-search', 'embeddings', 'mcp'],
 80, false, 'approved'),

-- ─── SKILLS (10) ─────────────────────────────────────────────────────────────

('anthropic-official-skills',
 'Anthropic Official Skills',
 'The official Anthropic skills library — battle-tested markdown workflows for common dev tasks: code review, test generation, documentation, and refactoring.',
 NULL, 'skill',
 'https://github.com/anthropics/skills', 'anthropics', 'Anthropic',
 ARRAY['official', 'anthropic', 'skills', 'code-review', 'testing', 'docs'],
 1400, true, 'approved'),

('awesome-agent-skills',
 'Awesome Agent Skills',
 'VoltAgent''s curated collection of Claude Code skills with a focus on agentic workflows — multi-step automations, research tasks, and complex code generation patterns.',
 NULL, 'skill',
 'https://github.com/VoltAgent/awesome-agent-skills', 'VoltAgent', 'VoltAgent',
 ARRAY['agentic', 'workflows', 'multi-step', 'automation', 'skills'],
 120, true, 'approved'),

('composio-claude-skills',
 'Composio Claude Skills',
 'ComposioHQ''s library of Claude Code skills for integrating with external services — pre-built automations for GitHub, Jira, Slack, and 200+ other tools.',
 NULL, 'skill',
 'https://github.com/ComposioHQ/awesome-claude-skills', 'ComposioHQ', 'Composio',
 ARRAY['composio', 'integrations', 'external-services', 'automation', 'skills'],
 150, false, 'approved'),

('karanb192-claude-skills',
 'karanb192 Claude Skills',
 'A practical collection of Claude Code skills focused on real-world dev workflows — PR reviews, dependency analysis, security audits, and architecture diagrams.',
 NULL, 'skill',
 'https://github.com/karanb192/awesome-claude-skills', 'karanb192', 'Karan B',
 ARRAY['pr-review', 'security', 'architecture', 'dependency-analysis', 'skills'],
 90, false, 'approved'),

('claude-scientific-skills',
 'Claude Scientific Skills',
 'Specialized Claude Code skills for scientific computing and data analysis — data cleaning, statistical analysis, visualization, and research paper summaries.',
 NULL, 'skill',
 'https://github.com/K-Dense-AI/claude-scientific-skills', 'K-Dense-AI', 'K-Dense AI',
 ARRAY['scientific', 'data-analysis', 'statistics', 'visualization', 'research', 'skills'],
 70, false, 'approved'),

('daymade-claude-skills',
 'Daymade Claude Skills',
 'Focused set of Claude Code skills for SaaS product teams — user story writing, feature spec generation, API design, and sprint planning automations.',
 NULL, 'skill',
 'https://github.com/daymade/claude-code-skills', 'daymade', 'Daymade',
 ARRAY['saas', 'product', 'user-stories', 'api-design', 'sprint', 'skills'],
 50, false, 'approved'),

('jezweb-claude-skills',
 'Jezweb Claude Skills',
 'Web agency-focused Claude Code skills: CMS content migrations, WordPress theming, accessibility audits, and client-ready deliverable generation.',
 NULL, 'skill',
 'https://github.com/jezweb/claude-skills', 'jezweb', 'Jezweb',
 ARRAY['wordpress', 'cms', 'web-agency', 'accessibility', 'content', 'skills'],
 30, false, 'approved'),

('mindrally-skills',
 'Mindrally Skills',
 'Mindrally''s Claude Code skills for cognitive productivity: meeting summarization, decision documentation, research synthesis, and knowledge base building.',
 NULL, 'skill',
 'https://github.com/Mindrally/skills', 'Mindrally', 'Mindrally',
 ARRAY['productivity', 'meetings', 'research', 'knowledge-base', 'skills'],
 60, false, 'approved'),

('scaffolding-skill',
 'Project Scaffolding Skill',
 'A Claude Code skill that generates full project scaffolds on demand — Next.js, FastAPI, Go microservices, and more with opinionated best-practice structures.',
 NULL, 'skill',
 'https://github.com/hmohamed01/Claude-Code-Scaffolding-Skill', 'hmohamed01', 'H Mohamed',
 ARRAY['scaffolding', 'project-setup', 'nextjs', 'fastapi', 'boilerplate', 'skills'],
 45, false, 'approved'),

('alirezarezvani-claude-skills',
 'Alirezarezvani Claude Skills',
 'A collection of Persian-language and bilingual Claude Code skills for localization, translation automation, and RTL layout generation tasks.',
 NULL, 'skill',
 'https://github.com/alirezarezvani/claude-skills', 'alirezarezvani', 'Alireza Rezvani',
 ARRAY['localization', 'translation', 'rtl', 'persian', 'i18n', 'skills'],
 40, false, 'approved'),

-- ─── HOOKS (8) ───────────────────────────────────────────────────────────────

('claude-code-hooks-collection',
 'Claude Code Hooks Collection',
 'karanb192''s comprehensive hooks library — pre/post tool hooks for git automation, test runners, linting enforcement, session logging, and notification alerts.',
 NULL, 'hook',
 'https://github.com/karanb192/claude-code-hooks', 'karanb192', 'Karan B',
 ARRAY['hooks', 'git', 'linting', 'testing', 'notifications', 'logging'],
 200, true, 'approved'),

('hooks-multi-agent-observability',
 'Multi-Agent Observability Hooks',
 'Hooks for observing and debugging multi-agent Claude Code sessions — trace inter-agent messages, log tool calls, visualize agent graphs, and detect loops.',
 NULL, 'hook',
 'https://github.com/disler/claude-code-hooks-multi-agent-observability', 'disler', 'Disler',
 ARRAY['observability', 'multi-agent', 'tracing', 'debugging', 'visualization', 'hooks'],
 120, true, 'approved'),

('hooks-mastery',
 'Claude Code Hooks Mastery',
 'A tutorial-style hooks repository with progressive examples from basic to advanced — includes patterns for security gates, auto-formatters, and CI integrations.',
 NULL, 'hook',
 'https://github.com/disler/claude-code-hooks-mastery', 'disler', 'Disler',
 ARRAY['hooks', 'tutorial', 'patterns', 'security', 'formatting', 'ci'],
 80, false, 'approved'),

('claude-code-otel',
 'Claude Code OpenTelemetry',
 'OpenTelemetry hooks for Claude Code — emit spans and metrics to any OTEL collector, enabling production-grade observability for your AI coding sessions.',
 NULL, 'hook',
 'https://github.com/ColeMurray/claude-code-otel', 'ColeMurray', 'Cole Murray',
 ARRAY['opentelemetry', 'otel', 'observability', 'metrics', 'tracing', 'hooks'],
 140, false, 'approved'),

('claude-telemetry',
 'Claude Telemetry',
 'TechNickAI''s hooks for collecting and exporting Claude Code telemetry — session duration, token counts, tool usage stats, and cost tracking.',
 NULL, 'hook',
 'https://github.com/TechNickAI/claude_telemetry', 'TechNickAI', 'TechNick AI',
 ARRAY['telemetry', 'cost-tracking', 'token-usage', 'analytics', 'hooks'],
 110, false, 'approved'),

('claude-usage-monitor',
 'Claude Code Usage Monitor',
 'Hooks that monitor and enforce Claude Code API usage limits — track daily token spend, set budget alerts, and auto-pause when limits are reached.',
 NULL, 'hook',
 'https://github.com/Maciek-roboblog/Claude-Code-Usage-Monitor', 'Maciek-roboblog', 'Maciek',
 ARRAY['usage', 'budget', 'limits', 'monitoring', 'cost', 'hooks'],
 50, false, 'approved'),

('johnlindquist-claude-hooks',
 'johnlindquist Claude Hooks',
 'Script Kit-style Claude Code hooks by John Lindquist — quick-launch automations, editor integrations, and interactive prompts triggered by Claude events.',
 NULL, 'hook',
 'https://github.com/johnlindquist/claude-hooks', 'johnlindquist', 'John Lindquist',
 ARRAY['script-kit', 'automation', 'editor-integration', 'interactive', 'hooks'],
 60, false, 'approved'),

('plankton-quality-hooks',
 'Plankton Quality Hooks',
 'alexfazio''s code quality hooks — automatically run formatters, linters, and type checkers after every file edit, blocking commits with quality regressions.',
 NULL, 'hook',
 'https://github.com/alexfazio/plankton', 'alexfazio', 'Alex Fazio',
 ARRAY['code-quality', 'linting', 'formatting', 'type-checking', 'gates', 'hooks'],
 35, false, 'approved'),

-- ─── AGENTS (8) ──────────────────────────────────────────────────────────────

('awesome-claude-code-subagents',
 'Awesome Claude Code Subagents',
 'VoltAgent''s curated collection of Claude Code subagent definitions — specialized roles for QA, security, DevOps, architecture review, and code generation.',
 NULL, 'agent',
 'https://github.com/VoltAgent/awesome-claude-code-subagents', 'VoltAgent', 'VoltAgent',
 ARRAY['subagents', 'roles', 'qa', 'security', 'devops', 'curated'],
 300, true, 'approved'),

('agents-claude-code',
 'Agents for Claude Code',
 'lodetomasi''s role-based agent library — frontend specialist, backend engineer, database architect, and more. Drop-in agent definitions for common engineering roles.',
 NULL, 'agent',
 'https://github.com/lodetomasi/agents-claude-code', 'lodetomasi', 'Lodetomasi',
 ARRAY['agents', 'roles', 'frontend', 'backend', 'database', 'engineering'],
 150, false, 'approved'),

('claude-command-suite',
 'Claude Command Suite',
 'qdhenry''s all-in-one agent + command collection — pre-built sub-agents paired with slash commands for a complete Claude Code workflow out of the box.',
 NULL, 'agent',
 'https://github.com/qdhenry/Claude-Command-Suite', 'qdhenry', 'QD Henry',
 ARRAY['agents', 'commands', 'workflow', 'all-in-one', 'suite'],
 140, false, 'approved'),

('list-of-claude-agents',
 'A List of Claude Code Agents',
 'hesreallyhim''s curated list of community-built Claude Code agent definitions — searchable by task type with links, descriptions, and quality ratings.',
 NULL, 'agent',
 'https://github.com/hesreallyhim/a-list-of-claude-code-agents', 'hesreallyhim', 'hesreallyhim',
 ARRAY['awesome-list', 'agents', 'curated', 'directory', 'community'],
 110, false, 'approved'),

('wshobson-agents',
 'wshobson Agents',
 'wshobson''s production-tested agent definitions covering ML engineering, data pipelines, infrastructure automation, and API integration tasks.',
 NULL, 'agent',
 'https://github.com/wshobson/agents', 'wshobson', 'wshobson',
 ARRAY['agents', 'ml', 'data-pipelines', 'infrastructure', 'api'],
 90, false, 'approved'),

('vizra-claude-agents',
 'Vizra Claude Code Agents',
 'vizra-ai''s enterprise agent templates — compliance checker, performance analyst, security auditor, and architecture reviewer with structured output formats.',
 NULL, 'agent',
 'https://github.com/vizra-ai/claude-code-agents', 'vizra-ai', 'Vizra AI',
 ARRAY['agents', 'enterprise', 'compliance', 'security', 'architecture', 'performance'],
 80, false, 'approved'),

('php-claude-agents',
 'PHP Claude Agents',
 'Specialized Claude Code agents for PHP and Laravel development — Eloquent ORM expert, Artisan command generator, and PHPUnit test writer agents.',
 NULL, 'agent',
 'https://github.com/atournayre/claude-agents', 'atournayre', 'atournayre',
 ARRAY['php', 'laravel', 'eloquent', 'phpunit', 'agents'],
 25, false, 'approved'),

('dl-ezo-sub-agents',
 'dl-ezo Sub-Agents',
 'dl-ezo''s focused sub-agent collection for full-stack projects — React component builder, API designer, SQL schema writer, and deployment configurator.',
 NULL, 'agent',
 'https://github.com/dl-ezo/claude-code-sub-agents', 'dl-ezo', 'dl-ezo',
 ARRAY['sub-agents', 'fullstack', 'react', 'sql', 'deployment', 'api'],
 35, false, 'approved'),

-- ─── CONFIGS (8) ─────────────────────────────────────────────────────────────

('trailofbits-claude-config',
 'Trail of Bits Claude Config',
 'Security-hardened CLAUDE.md configuration from Trail of Bits — enforces secure coding practices, rejects dangerous patterns, and adds security-review prompts.',
 NULL, 'config',
 'https://github.com/trailofbits/claude-code-config', 'trailofbits', 'Trail of Bits',
 ARRAY['security', 'secure-coding', 'trailofbits', 'config', 'claude-md'],
 60, true, 'approved'),

('agent-rules',
 'Agent Rules',
 'steipete''s opinionated CLAUDE.md rules for large codebases — enforces architecture boundaries, naming conventions, test requirements, and PR hygiene.',
 NULL, 'config',
 'https://github.com/steipete/agent-rules', 'steipete', 'Peter Steinberger',
 ARRAY['rules', 'architecture', 'conventions', 'testing', 'config', 'claude-md'],
 80, false, 'approved'),

('awesome-claude-md',
 'Awesome CLAUDE.md',
 'A curated collection of CLAUDE.md configuration files from real projects — monorepos, SaaS apps, open-source libraries, and enterprise codebases.',
 NULL, 'config',
 'https://github.com/josix/awesome-claude-md', 'josix', 'Josix',
 ARRAY['awesome-list', 'claude-md', 'examples', 'curated', 'config'],
 50, false, 'approved'),

('claude-md-templates',
 'CLAUDE.md Templates',
 'Ready-to-use CLAUDE.md templates for popular stacks: Next.js, Django, Rails, FastAPI, Spring Boot, and more — with tech-specific rules and conventions.',
 NULL, 'config',
 'https://github.com/abhishekray07/claude-md-templates', 'abhishekray07', 'Abhishek Ray',
 ARRAY['templates', 'nextjs', 'django', 'rails', 'fastapi', 'config', 'claude-md'],
 30, false, 'approved'),

('jarrodwatts-claude-config',
 'jarrodwatts Claude Config',
 'jarrodwatts'' personal Claude Code config for Web3 development — includes rules for Solidity, TypeScript, wagmi, and thirdweb project conventions.',
 NULL, 'config',
 'https://github.com/jarrodwatts/claude-code-config', 'jarrodwatts', 'Jarrod Watts',
 ARRAY['web3', 'solidity', 'typescript', 'wagmi', 'thirdweb', 'config'],
 25, false, 'approved'),

('claude-starter-kit',
 'Claude Starter Kit',
 'serpro69''s opinionated starter config for Claude Code — batteries-included CLAUDE.md with git conventions, commit message format, test requirements, and style guides.',
 NULL, 'config',
 'https://github.com/serpro69/claude-starter-kit', 'serpro69', 'serpro69',
 ARRAY['starter', 'git-conventions', 'commit-format', 'style-guide', 'config'],
 70, false, 'approved'),

('cursor2claude',
 'cursor2claude',
 'Migrate your Cursor AI rules to Claude Code config — automatically converts .cursorrules to CLAUDE.md with rule equivalence mapping and manual review hints.',
 NULL, 'config',
 'https://github.com/hcastro/cursor2claude', 'hcastro', 'H Castro',
 ARRAY['cursor', 'migration', 'cursorrules', 'claude-md', 'converter', 'config'],
 45, false, 'approved'),

('centminmod-claude-setup',
 'centminmod Claude Setup',
 'centminmod''s production server Claude Code setup — optimized configs for LEMP stack development, performance tuning, and server administration tasks.',
 NULL, 'config',
 'https://github.com/centminmod/my-claude-code-setup', 'centminmod', 'centminmod',
 ARRAY['lemp', 'server', 'nginx', 'mysql', 'performance', 'config'],
 30, false, 'approved'),

-- ─── HARNESSES (8) ───────────────────────────────────────────────────────────

('sparc-framework',
 'SPARC Framework',
 'Specification, Pseudocode, Architecture, Refinement, Completion — ruvnet''s structured AI-driven development methodology implemented as a Claude Code harness.',
 NULL, 'harness',
 'https://github.com/ruvnet/sparc', 'ruvnet', 'Reuven Cohen',
 ARRAY['sparc', 'methodology', 'architecture', 'specification', 'tdd', 'framework'],
 380, true, 'approved'),

('superclaude-framework',
 'SuperClaude Framework',
 'SuperClaude is an opinionated Claude Code configuration framework — structured personas, cognitive flags, and domain-specific modes for consistent AI behavior.',
 NULL, 'harness',
 'https://github.com/SuperClaude-Org/SuperClaude_Framework', 'SuperClaude-Org', 'SuperClaude',
 ARRAY['personas', 'cognitive-modes', 'configuration', 'framework', 'behavior'],
 90, false, 'approved'),

('awesome-claude-code-toolkit',
 'Awesome Claude Code Toolkit',
 'rohitg00''s comprehensive toolkit of Claude Code resources — curated MCP servers, hooks patterns, agent templates, and deployment guides for production use.',
 NULL, 'harness',
 'https://github.com/rohitg00/awesome-claude-code-toolkit', 'rohitg00', 'Rohit Ghumare',
 ARRAY['toolkit', 'curated', 'mcp', 'hooks', 'agents', 'production'],
 120, false, 'approved'),

('claude-code-harness',
 'Claude Code Harness',
 'Chachamaru127''s structured harness for managing multi-file Claude Code projects — task queues, context budgeting, file dependency graphs, and session checkpoints.',
 NULL, 'harness',
 'https://github.com/Chachamaru127/claude-code-harness', 'Chachamaru127', 'Chachamaru127',
 ARRAY['task-queue', 'context-budgeting', 'dependency-graph', 'checkpoints', 'harness'],
 100, false, 'approved'),

('claude-workflow',
 'Claude Code Workflow',
 'catlog22''s workflow harness for product teams — sprint-based task management, issue-to-code automation, and structured PR generation workflows.',
 NULL, 'harness',
 'https://github.com/catlog22/Claude-Code-Workflow', 'catlog22', 'catlog22',
 ARRAY['workflow', 'sprint', 'product', 'automation', 'pr-generation', 'harness'],
 50, false, 'approved'),

('agentic-framework',
 'Claude Agentic Framework',
 'dralgorhythm''s lightweight agentic framework for Claude Code — composable pipelines, tool chaining, and structured output validation for reliable code generation.',
 NULL, 'harness',
 'https://github.com/dralgorhythm/claude-agentic-framework', 'dralgorhythm', 'dralgorhythm',
 ARRAY['agentic', 'pipelines', 'tool-chaining', 'validation', 'composable', 'harness'],
 40, false, 'approved'),

('awesome-claude-code-plugins',
 'Awesome Claude Code Plugins',
 'A community-curated directory of the best Claude Code plugins, harnesses, and tools — organized by use case with install instructions and community ratings.',
 NULL, 'harness',
 'https://github.com/ccplugins/awesome-claude-code-plugins', 'ccplugins', 'CC Plugins',
 ARRAY['awesome-list', 'directory', 'plugins', 'community', 'curated'],
 250, false, 'approved'),

('claude-engineer',
 'Claude Engineer',
 'Doriandarko''s autonomous software engineering harness — give Claude a task and it plans, implements, tests, and iterates until the feature is complete.',
 NULL, 'harness',
 'https://github.com/Doriandarko/claude-engineer', 'Doriandarko', 'Pietro Schirano',
 ARRAY['autonomous', 'engineering', 'planning', 'implementation', 'iteration', 'harness'],
 200, false, 'approved'),

-- ─── COMMANDS (6) ────────────────────────────────────────────────────────────

('wshobson-commands',
 'wshobson Commands',
 'wshobson''s production slash command library — /analyze, /optimize, /document, /test, /review, and more. Clean, composable commands for everyday engineering.',
 NULL, 'command',
 'https://github.com/wshobson/commands', 'wshobson', 'wshobson',
 ARRAY['slash-commands', 'analyze', 'optimize', 'document', 'test', 'review'],
 100, true, 'approved'),

('artemgetmann-slash-commands',
 'artemgetmann Slash Commands',
 'Artemgetmann''s slash commands for rapid development — scaffold generators, boilerplate creators, and refactoring helpers for TypeScript and Python projects.',
 NULL, 'command',
 'https://github.com/artemgetmann/claude-slash-commands', 'artemgetmann', 'Artem Getmann',
 ARRAY['scaffold', 'boilerplate', 'refactoring', 'typescript', 'python', 'slash-commands'],
 45, false, 'approved'),

('danielrosehill-slash-commands',
 'Daniel Rosehill Slash Commands',
 'danielrosehill''s practical slash commands for content creators and technical writers — outline generators, SEO optimizers, and document formatter commands.',
 NULL, 'command',
 'https://github.com/danielrosehill/Claude-Slash-Commands', 'danielrosehill', 'Daniel Rosehill',
 ARRAY['content', 'writing', 'seo', 'documentation', 'formatter', 'slash-commands'],
 30, false, 'approved'),

('claude-sessions',
 'Claude Sessions',
 'iannuttall''s session management commands — save and restore Claude Code conversation state, tag sessions by project, and resume work exactly where you left off.',
 NULL, 'command',
 'https://github.com/iannuttall/claude-sessions', 'iannuttall', 'Ian Nuttall',
 ARRAY['sessions', 'state', 'resume', 'conversation', 'persistence', 'slash-commands'],
 35, false, 'approved'),

('spec-to-code',
 'Spec to Code',
 'michael-borck''s /spec-to-code command — paste a feature spec and Claude generates a fully structured implementation plan with TDD anchors and acceptance criteria.',
 NULL, 'command',
 'https://github.com/michael-borck/spec-to-code', 'michael-borck', 'Michael Borck',
 ARRAY['spec', 'tdd', 'planning', 'acceptance-criteria', 'bdd', 'slash-commands'],
 25, false, 'approved'),

('spec-workflow',
 'Claude Code Spec Workflow',
 'Pimzino''s spec-driven development workflow — structured commands to write specs, validate them, generate code, and track feature completion in a consistent loop.',
 NULL, 'command',
 'https://github.com/Pimzino/claude-code-spec-workflow', 'Pimzino', 'Pimzino',
 ARRAY['spec-driven', 'workflow', 'validation', 'feature-tracking', 'tdd', 'slash-commands'],
 40, false, 'approved'),

-- ─── IDE PLUGINS (5) ─────────────────────────────────────────────────────────

('claudecode-nvim',
 'claudecode.nvim (Coder)',
 'Official Coder Neovim plugin for Claude Code — native nvim integration with terminal splits, file context injection, selection-aware prompts, and LSP integration.',
 NULL, 'ide-plugin',
 'https://github.com/coder/claudecode.nvim', 'coder', 'Coder',
 ARRAY['neovim', 'nvim', 'ide', 'terminal', 'lsp', 'coder'],
 70, true, 'approved'),

('claude-code-nvim',
 'claude-code.nvim',
 'greggh''s lightweight Neovim plugin for Claude Code — open Claude in a floating terminal, pass visual selections as context, and bind to custom keymaps.',
 NULL, 'ide-plugin',
 'https://github.com/greggh/claude-code.nvim', 'greggh', 'greggh',
 ARRAY['neovim', 'nvim', 'floating-terminal', 'keymaps', 'selection', 'ide'],
 50, false, 'approved'),

('claude-code-plus-jetbrains',
 'Claude Code Plus (JetBrains)',
 'JetBrains IDE plugin that embeds Claude Code — run Claude from IntelliJ IDEA, WebStorm, PyCharm, and GoLand with native tool windows and file context.',
 NULL, 'ide-plugin',
 'https://github.com/touwaeriol/claude-code-plus', 'touwaeriol', 'touwaeriol',
 ARRAY['jetbrains', 'intellij', 'webstorm', 'pycharm', 'ide', 'plugin'],
 40, false, 'approved'),

('claude-code-action',
 'Claude Code Action',
 'Official Anthropic GitHub Action — add Claude Code as a CI reviewer that comments on PRs, fixes failing tests, and implements requested changes automatically.',
 NULL, 'ide-plugin',
 'https://github.com/anthropics/claude-code-action', 'anthropics', 'Anthropic',
 ARRAY['github-actions', 'ci', 'pr-review', 'official', 'anthropic', 'automation'],
 1200, true, 'approved'),

('claude-code-security-review',
 'Claude Code Security Review Action',
 'Official Anthropic GitHub Action for automated security review — Claude scans every PR for vulnerabilities, secrets exposure, and OWASP top 10 issues.',
 NULL, 'ide-plugin',
 'https://github.com/anthropics/claude-code-security-review', 'anthropics', 'Anthropic',
 ARRAY['security', 'github-actions', 'vulnerability-scanning', 'owasp', 'official', 'pr'],
 350, false, 'approved'),

-- ─── PLUGINS (5) ─────────────────────────────────────────────────────────────

('claude-code-templates-cli',
 'Claude Code Templates CLI',
 'davila7''s CLI tool to browse and install Claude Code templates — search by category, preview before install, and manage installed templates from the terminal.',
 NULL, 'plugin',
 'https://github.com/davila7/claude-code-templates', 'davila7', 'Daniel Avila',
 ARRAY['cli', 'templates', 'install', 'browse', 'package-manager'],
 80, false, 'approved'),

('claude-code-config-tui',
 'Claude Code Config TUI',
 'joeyism''s terminal UI for managing Claude Code settings — browse MCP servers, toggle hooks, edit CLAUDE.md, and manage permissions from an interactive TUI.',
 NULL, 'plugin',
 'https://github.com/joeyism/claude-code-config', 'joeyism', 'Joey Sham',
 ARRAY['tui', 'terminal-ui', 'settings', 'mcp', 'configuration', 'interactive'],
 50, false, 'approved'),

('mcp-server-selector',
 'MCP Server Selector',
 'henkisdabro''s interactive tool for discovering and configuring MCP servers — search by capability, auto-generate config JSON, and test server connectivity.',
 NULL, 'plugin',
 'https://github.com/henkisdabro/Claude-Code-MCP-Server-Selector', 'henkisdabro', 'Henkis Dabro',
 ARRAY['mcp', 'discovery', 'configuration', 'server-selector', 'json', 'plugin'],
 60, false, 'approved'),

('claude-supermemory',
 'Claude Supermemory',
 'supermemoryai''s persistent memory plugin for Claude Code — automatically indexes your codebases, conversations, and notes for semantic search across all sessions.',
 NULL, 'plugin',
 'https://github.com/supermemoryai/claude-supermemory', 'supermemoryai', 'Supermemory AI',
 ARRAY['memory', 'persistence', 'semantic-search', 'indexing', 'cross-session', 'plugin'],
 70, false, 'approved'),

('claudebox',
 'ClaudeBox',
 'RchGrav''s sandboxed Docker environment for Claude Code — isolated containers per project with configurable resource limits, volume mounts, and network policies.',
 NULL, 'plugin',
 'https://github.com/RchGrav/claudebox', 'RchGrav', 'RchGrav',
 ARRAY['docker', 'sandbox', 'isolation', 'containers', 'security', 'plugin'],
 45, false, 'approved');

-- Ensure vote counts are correct (safety measure)
update public.mods m
set vote_count = (select count(*) from public.votes v where v.mod_id = m.id);
