-- Seed expansion 2: ~57 additional curated mods for claudemod.com
-- Run order: after 004_seed_expansion.sql
-- Star counts are approximate estimates; update via: UPDATE public.mods SET github_stars = <n> WHERE slug = '<slug>';

insert into public.mods (
  slug, name, description, long_description, category,
  github_url, author_github, author_name,
  tags, github_stars, is_featured, status
) values

-- ─── MCP SERVERS (18) ────────────────────────────────────────────────────────

('aws-mcp',
 'AWS MCP Servers',
 'Official AWS Labs collection of MCP servers — CDK infrastructure generation, Bedrock model access, AWS docs lookup, cost analysis, and more in a single monorepo.',
 NULL, 'mcp-server',
 'https://github.com/awslabs/mcp', 'awslabs', 'AWS Labs',
 ARRAY['aws', 'cdk', 'bedrock', 'cloud', 'official', 'infrastructure', 'mcp'],
 800, true, 'approved'),

('supabase-mcp',
 'Supabase MCP',
 'Official Supabase community MCP server — manage tables, run SQL queries, apply migrations, inspect schemas, and interact with your Supabase project directly from Claude.',
 NULL, 'mcp-server',
 'https://github.com/supabase-community/supabase-mcp', 'supabase-community', 'Supabase Community',
 ARRAY['supabase', 'postgres', 'database', 'migrations', 'official', 'mcp'],
 1200, true, 'approved'),

('redis-mcp',
 'Redis MCP',
 'Official Redis MCP server — get and set keys, work with hashes, lists, sets, and sorted sets, publish/subscribe to channels, and inspect streams from within Claude.',
 NULL, 'mcp-server',
 'https://github.com/redis/mcp-redis', 'redis', 'Redis',
 ARRAY['redis', 'cache', 'pub-sub', 'streams', 'official', 'mcp'],
 400, true, 'approved'),

('mcp-server-qdrant',
 'Qdrant MCP',
 'Official Qdrant vector database MCP server — upsert vectors, run semantic search, manage collections, and build RAG pipelines without leaving Claude.',
 NULL, 'mcp-server',
 'https://github.com/qdrant/mcp-server-qdrant', 'qdrant', 'Qdrant',
 ARRAY['qdrant', 'vector-db', 'semantic-search', 'rag', 'embeddings', 'official', 'mcp'],
 600, false, 'approved'),

('mongodb-mcp-server',
 'MongoDB MCP',
 'Official MongoDB MCP server — CRUD operations, aggregation pipelines, index management, and schema inspection across your MongoDB databases from Claude.',
 NULL, 'mcp-server',
 'https://github.com/mongodb-js/mongodb-mcp-server', 'mongodb-js', 'MongoDB',
 ARRAY['mongodb', 'nosql', 'database', 'aggregation', 'official', 'mcp'],
 700, true, 'approved'),

('mcp-neo4j',
 'Neo4j MCP',
 'Neo4j graph database MCP server — run Cypher queries, build knowledge graph memory, explore schema, and traverse relationships directly from Claude.',
 NULL, 'mcp-server',
 'https://github.com/neo4j-contrib/mcp-neo4j', 'neo4j-contrib', 'Neo4j',
 ARRAY['neo4j', 'graph-db', 'cypher', 'knowledge-graph', 'relationships', 'mcp'],
 300, false, 'approved'),

('mcp-clickhouse',
 'ClickHouse MCP',
 'Official ClickHouse MCP server — query columnar analytics databases at scale, inspect tables, run aggregations, and explore OLAP data directly from Claude.',
 NULL, 'mcp-server',
 'https://github.com/ClickHouse/mcp-clickhouse', 'ClickHouse', 'ClickHouse',
 ARRAY['clickhouse', 'analytics', 'olap', 'columnar', 'official', 'mcp'],
 250, false, 'approved'),

('snowflake-mcp',
 'Snowflake MCP',
 'Official Snowflake MCP server with Cortex Agents support — query your data cloud warehouse, manage databases, and leverage Snowflake AI capabilities from Claude.',
 NULL, 'mcp-server',
 'https://github.com/Snowflake-Labs/mcp', 'Snowflake-Labs', 'Snowflake',
 ARRAY['snowflake', 'data-warehouse', 'cloud', 'cortex', 'official', 'mcp'],
 350, false, 'approved'),

('dbt-mcp',
 'dbt MCP',
 'Official dbt MCP server — run dbt models, parse lineage graphs, inspect compiled SQL, access project docs, and debug transformations without leaving Claude.',
 NULL, 'mcp-server',
 'https://github.com/dbt-labs/dbt-mcp', 'dbt-labs', 'dbt Labs',
 ARRAY['dbt', 'data-transformation', 'lineage', 'sql', 'analytics', 'official', 'mcp'],
 450, false, 'approved'),

('chroma-mcp',
 'Chroma MCP',
 'Official Chroma vector database MCP server — create and manage collections, upsert embeddings, run semantic search, and build local RAG systems from Claude.',
 NULL, 'mcp-server',
 'https://github.com/chroma-core/chroma-mcp', 'chroma-core', 'Chroma',
 ARRAY['chroma', 'vector-db', 'embeddings', 'rag', 'semantic-search', 'official', 'mcp'],
 500, false, 'approved'),

('e2b-mcp-server',
 'E2B Code Sandbox MCP',
 'Official E2B MCP server — execute arbitrary code in secure cloud sandboxes, run scripts in isolated environments, and get output back in Claude without local execution risks.',
 NULL, 'mcp-server',
 'https://github.com/e2b-dev/mcp-server', 'e2b-dev', 'E2B',
 ARRAY['e2b', 'sandbox', 'code-execution', 'cloud', 'secure', 'official', 'mcp'],
 600, false, 'approved'),

('azure-devops-mcp',
 'Azure DevOps MCP',
 'Official Microsoft Azure DevOps MCP server — manage pipelines, work items on boards, pull requests, and Azure Repos directly from Claude Code.',
 NULL, 'mcp-server',
 'https://github.com/microsoft/azure-devops-mcp', 'microsoft', 'Microsoft',
 ARRAY['azure', 'devops', 'pipelines', 'boards', 'microsoft', 'official', 'mcp'],
 400, false, 'approved'),

('pulumi-mcp-server',
 'Pulumi MCP',
 'Official Pulumi MCP server — manage cloud infrastructure programmatically, preview and deploy stacks, inspect resource graphs, and query the Pulumi Registry from Claude.',
 NULL, 'mcp-server',
 'https://github.com/pulumi/mcp-server', 'pulumi', 'Pulumi',
 ARRAY['pulumi', 'infrastructure', 'iac', 'cloud', 'official', 'mcp'],
 300, false, 'approved'),

('localstack-mcp-server',
 'LocalStack MCP',
 'LocalStack MCP server — test AWS services locally without real cloud costs. Spin up S3, Lambda, DynamoDB, SQS, and more in a local Docker environment via Claude.',
 NULL, 'mcp-server',
 'https://github.com/localstack/localstack-mcp-server', 'localstack', 'LocalStack',
 ARRAY['localstack', 'aws', 'local-dev', 'testing', 'docker', 'mcp'],
 200, false, 'approved'),

('brightdata-mcp',
 'BrightData MCP',
 'BrightData''s web data extraction MCP server — structured scraping at scale using BrightData''s residential proxy network, SERP API, and dataset marketplace.',
 NULL, 'mcp-server',
 'https://github.com/brightdata/brightdata-mcp', 'brightdata', 'BrightData',
 ARRAY['brightdata', 'web-scraping', 'proxies', 'serp', 'data-extraction', 'mcp'],
 350, false, 'approved'),

('google-workspace-mcp',
 'Google Workspace MCP',
 'Gmail, Calendar, Drive, Docs, Sheets, and Slides via a single MCP server — read emails, create events, edit spreadsheets, and manage Drive files from Claude.',
 NULL, 'mcp-server',
 'https://github.com/taylorwilsdon/google_workspace_mcp', 'taylorwilsdon', 'Taylor Wilsdon',
 ARRAY['google', 'gmail', 'calendar', 'drive', 'sheets', 'workspace', 'mcp'],
 300, false, 'approved'),

('basic-memory-mcp',
 'Basic Memory',
 'Local-first persistent memory MCP server — store notes, context, and knowledge as plain markdown files that Claude can read and write across all sessions.',
 NULL, 'mcp-server',
 'https://github.com/basicmachines-co/basic-memory', 'basicmachines-co', 'Basic Machines',
 ARRAY['memory', 'persistence', 'markdown', 'local-first', 'cross-session', 'mcp'],
 400, false, 'approved'),

('container-use-mcp',
 'Container Use (Dagger)',
 'Official Dagger MCP server — give Claude isolated container environments per task. Each agent gets its own container with configurable tools, filesystem, and network access.',
 NULL, 'mcp-server',
 'https://github.com/dagger/container-use', 'dagger', 'Dagger',
 ARRAY['dagger', 'containers', 'docker', 'isolation', 'official', 'multi-agent', 'mcp'],
 900, true, 'approved'),

-- ─── IDE PLUGINS (5) ─────────────────────────────────────────────────────────

('claude-code-el',
 'claude-code.el (Emacs)',
 'Emacs minor mode for Claude Code — open an embedded Claude terminal, send visual selections as context, and bind Claude workflows to Emacs key chords.',
 NULL, 'ide-plugin',
 'https://github.com/stevemolitor/claude-code.el', 'stevemolitor', 'Steve Molitor',
 ARRAY['emacs', 'elisp', 'terminal', 'ide', 'selection-context'],
 150, false, 'approved'),

('claude-code-ide-el',
 'claude-code-ide.el',
 'Project-aware Emacs IDE integration for Claude Code — injects project context, active buffer, and LSP diagnostics into Claude automatically for smarter suggestions.',
 NULL, 'ide-plugin',
 'https://github.com/manzaltu/claude-code-ide.el', 'manzaltu', 'manzaltu',
 ARRAY['emacs', 'elisp', 'lsp', 'project-context', 'ide'],
 100, false, 'approved'),

('claude-vim',
 'claude.vim',
 'Vim plugin for AI pair programming with Claude — deep Vim workflow integration with buffer-aware context, visual selection prompts, and native Vim keybindings.',
 NULL, 'ide-plugin',
 'https://github.com/pasky/claude.vim', 'pasky', 'Petr Baudiš',
 ARRAY['vim', 'neovim', 'ide', 'pair-programming', 'keybindings'],
 300, false, 'approved'),

('crystal-multiagent',
 'Crystal',
 'Visual multi-agent Claude Code client by Stravu — run parallel Claude Code sessions side by side, compare outputs with a diff viewer, and merge the best parts.',
 NULL, 'ide-plugin',
 'https://github.com/stravu/crystal', 'stravu', 'Stravu',
 ARRAY['multi-agent', 'parallel', 'diff-viewer', 'gui', 'sessions'],
 600, true, 'approved'),

('voicemode',
 'VoiceMode',
 'Voice input MCP server and hook for Claude Code — speak your prompts aloud, get voice alerts when Claude finishes, and navigate sessions hands-free.',
 NULL, 'ide-plugin',
 'https://github.com/mbailey/voicemode', 'mbailey', 'Mike Bailey',
 ARRAY['voice', 'speech', 'audio', 'hands-free', 'mcp', 'hook'],
 200, false, 'approved'),

-- ─── HARNESSES (6) ───────────────────────────────────────────────────────────

('claude-squad',
 'Claude Squad',
 'Multi-agent tmux orchestrator — spawn N isolated Claude Code sessions in parallel, each in its own git worktree, then merge the best results back to main.',
 NULL, 'harness',
 'https://github.com/smtg-ai/claude-squad', 'smtg-ai', 'SMTG AI',
 ARRAY['multi-agent', 'parallel', 'tmux', 'worktree', 'orchestration', 'harness'],
 1800, true, 'approved'),

('claude-swarm',
 'Claude Swarm',
 'Distributed Claude agent swarms — agents communicate via MCP, share tool access, and collaborate on complex tasks with configurable topology and role specialization.',
 NULL, 'harness',
 'https://github.com/parruda/claude-swarm', 'parruda', 'parruda',
 ARRAY['swarm', 'distributed', 'multi-agent', 'mcp', 'topology', 'harness'],
 500, false, 'approved'),

('claude-task-master',
 'Claude Task Master',
 'AI-powered task management harness — paste a PRD and Claude Task Master parses it into dependency-tracked tasks, assigns agents, and drives implementation end to end.',
 NULL, 'harness',
 'https://github.com/eyaltoledano/claude-task-master', 'eyaltoledano', 'Eyal Toledano',
 ARRAY['task-management', 'prd', 'dependency-tracking', 'planning', 'agentic', 'harness'],
 2000, true, 'approved'),

('claude-simone',
 'claude-simone',
 'Structured project management harness for Claude Code — define milestones and sprints in markdown, then run execution loops that drive Claude through each task.',
 NULL, 'harness',
 'https://github.com/Helmi/claude-simone', 'Helmi', 'Helmi',
 ARRAY['project-management', 'milestones', 'sprints', 'structured', 'harness'],
 400, false, 'approved'),

('serena',
 'Serena',
 'Autonomous coding agent using language servers for precise code navigation — Serena reads LSP symbols and references so Claude edits exactly the right code without guessing.',
 NULL, 'harness',
 'https://github.com/oraios/serena', 'oraios', 'Oraios',
 ARRAY['autonomous', 'lsp', 'code-navigation', 'symbols', 'references', 'harness'],
 600, false, 'approved'),

('claude-code-riper',
 'RIPER-5 Framework',
 'RIPER-5 methodology config for Claude Code — enforces the Research, Innovate, Plan, Execute, Review loop to prevent premature implementation and ensure thoughtful decisions.',
 NULL, 'harness',
 'https://github.com/tony/claude-code-riper-5', 'tony', 'Tony',
 ARRAY['riper', 'methodology', 'research', 'planning', 'review', 'harness'],
 300, false, 'approved'),

-- ─── SKILLS (9) ──────────────────────────────────────────────────────────────

('ecc-tdd-workflow',
 'ECC TDD Workflow',
 'Full TDD cycle skill from everything-claude-code — red-green-refactor loop with coverage gates, test-first enforcement, and structured commit checkpoints.',
 NULL, 'skill',
 'https://github.com/affaan-m/everything-claude-code/tree/main/skills/tdd-workflow', 'affaan-m', 'Affaan M',
 ARRAY['tdd', 'testing', 'red-green-refactor', 'coverage', 'workflow', 'skills'],
 500, false, 'approved'),

('ecc-frontend-patterns',
 'ECC Frontend Patterns',
 'React and Next.js component patterns skill from everything-claude-code — Tailwind utility conventions, accessibility checklists, and composable UI architecture.',
 NULL, 'skill',
 'https://github.com/affaan-m/everything-claude-code/tree/main/skills/frontend-patterns', 'affaan-m', 'Affaan M',
 ARRAY['react', 'nextjs', 'tailwind', 'accessibility', 'components', 'skills'],
 500, false, 'approved'),

('ecc-backend-patterns',
 'ECC Backend Patterns',
 'REST API design, database schema patterns, and caching strategy skill from everything-claude-code — opinionated conventions for building reliable backend services.',
 NULL, 'skill',
 'https://github.com/affaan-m/everything-claude-code/tree/main/skills/backend-patterns', 'affaan-m', 'Affaan M',
 ARRAY['rest-api', 'database', 'caching', 'backend', 'patterns', 'skills'],
 500, false, 'approved'),

('ecc-security-review',
 'ECC Security Review',
 'OWASP-aligned security checklist skill from everything-claude-code — scans code for injection flaws, auth issues, sensitive data exposure, and misconfigured dependencies.',
 NULL, 'skill',
 'https://github.com/affaan-m/everything-claude-code/tree/main/skills/security-review', 'affaan-m', 'Affaan M',
 ARRAY['security', 'owasp', 'vulnerabilities', 'audit', 'checklist', 'skills'],
 500, false, 'approved'),

('ecc-e2e-testing',
 'ECC E2E Testing',
 'Playwright end-to-end testing patterns skill from everything-claude-code — page object models, fixture management, CI integration, and cross-browser test strategies.',
 NULL, 'skill',
 'https://github.com/affaan-m/everything-claude-code/tree/main/skills/e2e-testing', 'affaan-m', 'Affaan M',
 ARRAY['playwright', 'e2e', 'testing', 'page-objects', 'ci', 'skills'],
 500, false, 'approved'),

('obra-superpowers',
 'Superpowers',
 'obra''s power-user Claude Code skill pack — deep workflow automations for veteran developers: smart refactoring, architecture analysis, and opinionated code generation.',
 NULL, 'skill',
 'https://github.com/obra/superpowers', 'obra', 'Jesse Vincent',
 ARRAY['power-user', 'refactoring', 'architecture', 'workflow', 'automation', 'skills'],
 300, false, 'approved'),

('trailofbits-skills',
 'Trail of Bits Skills',
 'Security-focused Claude Code skills from Trail of Bits — secure coding practices, audit checklists, threat modeling templates, and cryptography guidance.',
 NULL, 'skill',
 'https://github.com/trailofbits/skills', 'trailofbits', 'Trail of Bits',
 ARRAY['security', 'audit', 'threat-modeling', 'cryptography', 'trailofbits', 'skills'],
 200, false, 'approved'),

('cc-devops-skills',
 'DevOps Skills',
 'CI/CD pipeline generation, Docker and Kubernetes configuration, and deployment automation skills — covers GitHub Actions, GitLab CI, Helm charts, and Terraform modules.',
 NULL, 'skill',
 'https://github.com/akin-ozer/cc-devops-skills', 'akin-ozer', 'Akin Ozer',
 ARRAY['devops', 'ci-cd', 'docker', 'kubernetes', 'terraform', 'deployment', 'skills'],
 150, false, 'approved'),

('context-engineering-kit',
 'Context Engineering Kit',
 'Advanced context window management and prompt engineering toolkit — techniques for compressing context, prioritizing relevant files, and structuring long conversations.',
 NULL, 'skill',
 'https://github.com/NeoLabHQ/context-engineering-kit', 'NeoLabHQ', 'NeoLab',
 ARRAY['context-engineering', 'prompt-engineering', 'context-window', 'optimization', 'skills'],
 200, false, 'approved'),

-- ─── AGENTS (4) ───────────────────────────────────────────────────────────────

('ecc-agent-planner',
 'ECC Planner Agent',
 'Feature implementation planning agent from everything-claude-code — breaks down requirements into ordered tasks with TDD anchors, dependency graph, and acceptance criteria.',
 NULL, 'agent',
 'https://github.com/affaan-m/everything-claude-code/blob/main/agents/planner.md', 'affaan-m', 'Affaan M',
 ARRAY['planning', 'task-breakdown', 'tdd', 'dependency-graph', 'agents'],
 500, false, 'approved'),

('ecc-agent-architect',
 'ECC Architect Agent',
 'System design and architectural decision-making agent from everything-claude-code — evaluates trade-offs, proposes patterns, and produces architecture decision records.',
 NULL, 'agent',
 'https://github.com/affaan-m/everything-claude-code/blob/main/agents/architect.md', 'affaan-m', 'Affaan M',
 ARRAY['architecture', 'system-design', 'adr', 'patterns', 'trade-offs', 'agents'],
 500, false, 'approved'),

('ecc-agent-code-reviewer',
 'ECC Code Reviewer',
 'Quality, security, and style code review agent from everything-claude-code — enforces team conventions, catches anti-patterns, and produces structured review comments.',
 NULL, 'agent',
 'https://github.com/affaan-m/everything-claude-code/blob/main/agents/code-reviewer.md', 'affaan-m', 'Affaan M',
 ARRAY['code-review', 'quality', 'style', 'conventions', 'anti-patterns', 'agents'],
 500, false, 'approved'),

('ecc-agent-security-reviewer',
 'ECC Security Reviewer',
 'Vulnerability analysis and secure coding enforcement agent from everything-claude-code — OWASP top 10 scans, dependency audits, and remediation recommendations.',
 NULL, 'agent',
 'https://github.com/affaan-m/everything-claude-code/blob/main/agents/security-reviewer.md', 'affaan-m', 'Affaan M',
 ARRAY['security', 'vulnerability', 'owasp', 'dependency-audit', 'remediation', 'agents'],
 500, false, 'approved'),

-- ─── HOOKS (5) ───────────────────────────────────────────────────────────────

('claude-hooks-sdk',
 'Claude Hooks SDK',
 'PHP/Laravel-style hooks SDK for Claude Code — define, compose, and test hooks with a clean API, middleware chaining, and built-in test helpers.',
 NULL, 'hook',
 'https://github.com/beyondcode/claude-hooks-sdk', 'beyondcode', 'Beyond Code',
 ARRAY['php', 'laravel', 'sdk', 'middleware', 'composable', 'hooks'],
 300, false, 'approved'),

('tdd-guard',
 'TDD Guard',
 'Pre-tool hook that blocks code edits unless a failing test exists first — enforces strict test-first discipline by refusing file writes without a red test in scope.',
 NULL, 'hook',
 'https://github.com/nizos/tdd-guard', 'nizos', 'nizos',
 ARRAY['tdd', 'test-first', 'pre-tool', 'enforcement', 'discipline', 'hooks'],
 200, false, 'approved'),

('cchooks',
 'CCHooks',
 'A collection of practical Claude Code hooks — auto-lint on save, run tests after edits, validate commit messages, and send desktop notifications on task completion.',
 NULL, 'hook',
 'https://github.com/GowayLee/cchooks', 'GowayLee', 'GowayLee',
 ARRAY['linting', 'testing', 'notifications', 'commit-validation', 'auto-save', 'hooks'],
 150, false, 'approved'),

('typescript-hooks',
 'TypeScript Claude Hooks',
 'TypeScript-specific Claude Code hooks — run tsc type checking, ESLint, and Prettier enforcement after every edit so type errors never accumulate during a session.',
 NULL, 'hook',
 'https://github.com/bartolli/claude-code-typescript-hooks', 'bartolli', 'bartolli',
 ARRAY['typescript', 'eslint', 'prettier', 'type-checking', 'formatting', 'hooks'],
 100, false, 'approved'),

('claudio',
 'Claudio',
 'Audio notification hooks for Claude Code — get voice alerts when Claude finishes a task, needs your input, or hits an error. Never miss a completed session again.',
 NULL, 'hook',
 'https://github.com/ctoth/claudio', 'ctoth', 'ctoth',
 ARRAY['audio', 'notifications', 'voice', 'alerts', 'completion', 'hooks'],
 150, false, 'approved'),

-- ─── COMMANDS (4) ────────────────────────────────────────────────────────────

('prd-generator',
 'PRD Generator',
 'Slash command that generates a full Product Requirements Document from a short prompt — includes goals, user stories, technical constraints, success metrics, and open questions.',
 NULL, 'command',
 'https://github.com/dredozubov/prd-generator', 'dredozubov', 'dredozubov',
 ARRAY['prd', 'product', 'user-stories', 'requirements', 'documentation', 'slash-commands'],
 150, false, 'approved'),

('scopecraft-command',
 'Scopecraft Command',
 'Task-based slash commands for structured feature development — /create-task, /list-tasks, /next-task drive a disciplined workflow from spec to implementation.',
 NULL, 'command',
 'https://github.com/scopecraft/command', 'scopecraft', 'Scopecraft',
 ARRAY['task-management', 'structured', 'feature-development', 'workflow', 'slash-commands'],
 400, false, 'approved'),

('linux-desktop-commands',
 'Linux Desktop Commands',
 'Desktop integration slash commands for Linux — open files in apps, show system notifications, interact with the system tray, and control apps from Claude Code.',
 NULL, 'command',
 'https://github.com/danielrosehill/Claude-Code-Linux-Desktop-Slash-Commands', 'danielrosehill', 'Daniel Rosehill',
 ARRAY['linux', 'desktop', 'notifications', 'system-integration', 'slash-commands'],
 80, false, 'approved'),

('todo-slash-command',
 'Todo Command',
 'Simple /todo command that manages a session todo list within Claude Code — add, complete, and list tasks inline without leaving your coding flow.',
 NULL, 'command',
 'https://github.com/chrisleyva/todo-slash-command', 'chrisleyva', 'Chris Leyva',
 ARRAY['todo', 'task-list', 'productivity', 'session', 'slash-commands'],
 80, false, 'approved'),

-- ─── CONFIGS (3) ─────────────────────────────────────────────────────────────

('claude-code-system-prompts',
 'Claude Code System Prompts',
 'Curated CLAUDE.md system prompt variations for different coding styles and strictness levels — conservative, balanced, and aggressive modes with detailed trade-off notes.',
 NULL, 'config',
 'https://github.com/Piebald-AI/claude-code-system-prompts', 'Piebald-AI', 'Piebald AI',
 ARRAY['system-prompts', 'claude-md', 'strictness', 'coding-style', 'config'],
 200, false, 'approved'),

('claude-codex-settings',
 'Claude Codex Settings',
 'Sensible default Claude Code configuration focused on Python and ML projects — includes rules for type hints, docstrings, pytest patterns, and data science conventions.',
 NULL, 'config',
 'https://github.com/fcakyon/claude-codex-settings', 'fcakyon', 'fcakyon',
 ARRAY['python', 'ml', 'data-science', 'pytest', 'type-hints', 'config'],
 150, false, 'approved'),

('claude-code-mcp-enhanced',
 'Claude Code MCP Enhanced',
 'Enhanced MCP configuration with extended tooling and custom prompts for complex projects — pre-configured server bundles, permission profiles, and context injection rules.',
 NULL, 'config',
 'https://github.com/grahama1970/claude-code-mcp-enhanced', 'grahama1970', 'grahama1970',
 ARRAY['mcp', 'configuration', 'tooling', 'permissions', 'extended', 'config'],
 150, false, 'approved'),

-- ─── PLUGINS (3) ─────────────────────────────────────────────────────────────

('claudekit',
 'ClaudeKit',
 'CLI toolkit for Claude Code — install skills and hooks from the registry, manage configurations, snapshot and restore sessions, and scaffold new mod projects.',
 NULL, 'plugin',
 'https://github.com/carlrannaberg/claudekit', 'carlrannaberg', 'Carl Rannaberg',
 ARRAY['cli', 'toolkit', 'install', 'package-manager', 'scaffold', 'plugin'],
 400, false, 'approved'),

('recall',
 'Recall',
 'Persistent cross-session memory plugin for Claude Code — indexes files, git history, and past conversations so Claude can recall context from weeks ago instantly.',
 NULL, 'plugin',
 'https://github.com/zippoxer/recall', 'zippoxer', 'zippoxer',
 ARRAY['memory', 'persistence', 'indexing', 'cross-session', 'recall', 'plugin'],
 200, false, 'approved'),

('rulesync',
 'RuleSync',
 'Sync Claude Code rules across multiple projects — maintain a single source-of-truth CLAUDE.md and push updates to all your repos with one command.',
 NULL, 'plugin',
 'https://github.com/dyoshikawa/rulesync', 'dyoshikawa', 'dyoshikawa',
 ARRAY['rules', 'sync', 'claude-md', 'multi-project', 'consistency', 'plugin'],
 150, false, 'approved');

-- Ensure vote counts are correct (safety measure)
update public.mods m
set vote_count = (select count(*) from public.votes v where v.mod_id = m.id);
